### ISSUE TITLE
Use JSON-schema instead of kwalify

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-format#31]
kwalify becomes unreadable for complex schemas.

We can adopt a JSON schema standard, so long as we stick to the JSON subset of YAML. ProtoBuf may be a possibility if there is a standard mapping to JSON.

Further afield, SHACL may be worth considering

**Comment by cmungall** [comment]
Update: JSON Schema is looking more likely at this stage. Note we will still support YAML, but we will use the subset of YAML that is compatible with JSON (with some tweaks necessary for datetime types).

IDL/RPC frameworks such as Thrift, protobuf, etc are not appropriate as ppkts are designed to be used outside the scope of an API (e.g. files deposited in repositories like dryad). However, we will look at compatibility layers in the future, with swagger.io being a high priority.

**Comment by mjy** [comment]
for reference http://jsonapi.org/faq/ - looks like api is not relevant vs where you are at presently
