### ISSUE TITLE
Further refine evidence references

### ISSUE THREAD

**Issue by mellybelly** [phenopackets/phenopacket-format#34]
Currently, we have evidence on the phenotype profile:
phenotype_profile:
- entity: "doi: 10.1101/mcs.a000661#patient1"
  evidence:
    type: TAS # Traceable author statement
    source:
      id: "doi: 10.1101/mcs.a000661"
      title: "De novo pathogenic variants in CHAMP1 are associated with global developmental delay, intellectual disability, and dysmorphic facial features"

Does evidence go on any element? e.g. a phenotype profile, a genotype profile, a PED/Family reference? Does it go on individual phenotypes? Or does the whole phenopacket get just one or more evidence assertions?

We should also further decide how/which evidence codes to use and what source information should be described with different evidence codes. @mbrush can you help define a few. E.g. is TAS good here? For OMIM, the example has an IEA, for patient example1, it says "observation".

**Comment by cmungall** [comment]
The mapping between shortforms (e.g. TAS) and class IRIs should go in the LD-context #40
