### ISSUE TITLE
relationship to json:API

### ISSUE THREAD

**Issue by mjy** [phenopackets/phenopacket-format#39]
What is the relation of a phenopacket to the best practices described at http://jsonapi.org/

Are packets just nested under data: there?

M

**Comment by cmungall** [comment]
We're likely to use JSON Schema (follow #31 for this - comments welcome here).

I'm unclear as to compatibility layers between jsonapi and jsonschema. Seems someone asked this here but the question was not answered:
https://github.com/json-api/json-api/issues/271#issuecomment-54693102

**Comment by mjy** [comment]
Closing in favor following #31.
