### ISSUE TITLE
GSoC 2016 @ ga4gh.org

### ISSUE THREAD

**Issue by rohangoel96** [phenopackets/phenopacket-format#47]
@cmungall,  I wish to contribute to the project Phenotype exchange standard ( #6 at  https://docs.google.com/document/d/15yUku7fdR3x_nH3eziI3VgXzvkUQrcVeN7C4pwqk3nU/edit ) and participate in GSoC for ga4gh.org in same project. I have experience making web-applications and have worked with NodeJS, HTML, CSS, Javascript. I also am familiar with Python and network usage (HTTP, SSH). Please help me get started. 
I am sorry for opening an maybe irrelevant issue like this but the irc is dead and I have no replies to my mails.

**Comment by cmungall** [comment]
Thanks for your interest @rohangoel96! I have followed up with email.
